# Generated by Django 5.2.1 on 2025-06-02 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dialogue',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player'),
        ),
        migrations.AddField(
            model_name='session',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player'),
        ),
        migrations.AddField(
            model_name='discoveredclue',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.session'),
        ),
        migrations.AddField(
            model_name='dialogue',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.session'),
        ),
        migrations.AddField(
            model_name='accusation',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.session'),
        ),
        migrations.AddField(
            model_name='story',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.scenario'),
        ),
        migrations.AddField(
            model_name='session',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.story'),
        ),
        migrations.AddField(
            model_name='clue',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.story'),
        ),
        migrations.AddField(
            model_name='character',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.story'),
        ),
        migrations.AlterUniqueTogether(
            name='discoveredclue',
            unique_together={('session', 'clue')},
        ),
    ]
