# Generated by Django 5.2.1 on 2025-06-02 18:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharactersRevealClue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conditions', models.TextField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.character')),
                ('clue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.clue')),
            ],
        ),
    ]
