services:
  react-app:
    image: node:20-alpine
    ports:
      - 5173:5173
    working_dir: /app
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: sh -c "npm install && npm run dev -- --host"
    networks:
      - mindprod_network

networks:
  mindprod_network:
    driver: bridge
    external: true
