services:
  web:
    build: 
      context: .
      dockerfile: DockerFilePython/Dockerfile
    container_name: mindprod_api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/app
    ports:
      - ${WEB_PORTS}:8000
    depends_on:
      - db
    environment:
      - DEBUG=True
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - OLLAMA_URL=${OLLAMA_URL}
      - OLLAMA_MODEL_NAME=${OLLAMA_MODEL_NAME}
    networks:
      - mindprod_network

  ollama:
    build:
      context: .
      dockerfile: DockerFileOllama/Dockerfile
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    networks:
      - mindprod_network
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - mindprod_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: mindprod_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - mindprod_network

networks:
  mindprod_network:
    driver: bridge
    external: true

volumes:
  pgdata:
  pgadmin_data:
  ollama_data:
