# Generated by Django 5.2.1 on 2025-06-02 09:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('role_id', models.CharField(choices=[('suspect', 'Suspect'), ('witness', 'Witness')], max_length=20)),
                ('image_url', models.TextField()),
                ('is_guilty', models.BooleanField()),
                ('personality', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Clue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('image_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.TextField(unique=True)),
                ('image_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scenario', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('ended_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('playing', 'Playing'), ('finished', 'Finished')], max_length=20)),
                ('remaining_lives', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('resume', models.TextField()),
                ('image_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Accusation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('is_correct', models.BooleanField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.character')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterAttribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.character')),
                ('clue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.clue')),
            ],
        ),
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('character_answer', models.TextField()),
                ('player_question', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.character')),
            ],
        ),
        migrations.CreateModel(
            name='DiscoveredClue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.clue')),
            ],
        ),
    ]
