# Generated by Django 5.2.1 on 2025-06-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_charactersrevealclue'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='backstory',
            field=models.TextField(default=''),
        ),
    ]
