# Generated by Django 5.2.1 on 2025-06-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_character_backstory'),
    ]

    operations = [
        migrations.AddField(
            model_name='clue',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
