# Generated by Django 5.2.1 on 2025-06-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_clue_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accusation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
