# Generated by Django 5.2.1 on 2025-06-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_accusation_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactersrevealclue',
            name='revelations',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
