# Generated by Django 5.2.1 on 2025-06-15 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_charactersrevealclue_revelations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='game.player'),
        ),
    ]
